apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cadence
  region: us-east-1

nodeGroups:
  - name: ng
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 80
    ssh:
      allow: true
