;;; keybinds.el ---                                  -*- lexical-binding: t; -*-

(dolist (binding
         '(("C-<tab>"        . other-window)
           ("M-<up>"         . enlarge-window)
           ("M-<down>"       . shrink-window)
           ("M-<right>"      . enlarge-window-horizontally)
           ("M-<left>"       . shrink-window-horizontally)
           ("C-<up>"         . mc/mark-previous-like-this)
           ("C-<down>"       . mc/mark-next-like-this)
           ("C-c C-<down>"   . mc/mark-all-like-this)
           ("C-<escape>"     . mc/keyboard-quit)
           ("C-c b k"        . close-buffers-by-extension)
           ("C-x g"          . magit-status)
           ("C-c d f"        . 'my-ediff-files)
           ("C-c d b"        . 'my-ediff-buffers)
           ("C-s"            . consult-line)
           ("C-c s"          . consult-ripgrep)
           ("C-x b"          . consult-buffer)
           ("M-y"            . consult-yank-pop)
           ("C-c p f"        . consult-project-extra-find)
           ("C-c p g"        . consult-project-extra-ripgrep)
           ("C-c a"          . org-agenda)
           ("C-c c"          . org-capture)
           ("M-0"            . treemacs-select-window)
           ("C-x t t"        . treemacs)
           ("C-x t d"        . treemacs-select-directory)
           ("C-x t B"        . treemacs-bookmark)
           ("C-x t C-t"      . treemacs-find-file)
           ("C-x t M-t"      . treemacs-find-tag)
           ("C-c v"          . vterm)
           )
         )
  (global-set-key (kbd (car binding)) (cdr binding)))

(provide 'keys)
;;; keys.el ends here
